'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class [Default]

    '''<summary>
    '''btnStartNewCharacter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStartNewCharacter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLoadExistingCharacter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoadExistingCharacter As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNextAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNextAction As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCharacterName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCharacterName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCharacterName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCharacterName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCharacterLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCharacterLevel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCharacterLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCharacterLevel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblArchetype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArchetype As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlArchetype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlArchetype As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblPrimary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrimary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlPrimary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPrimary As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSecondary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSecondary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSecondary As Global.System.Web.UI.WebControls.DropDownList
End Class
